import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import React, { useState, useEffect, memo } from 'react';

import { Movie } from '@/types/movie';
import MovieList from '@/components/MovieList';

export default function Home() {

  const [decadeData, setDecadeData] = useState<{ decade: string, data: Movie[] }[]>([]);

  const API_KEY = "e6aa88b5ddb978bed15a2f5bf44010a0";
  const url = `https://api.themoviedb.org/3/movie/top_rated?api_key=${API_KEY}&language=en-US&page=1&include_adult=false`;

  useEffect(() => {
    console.log("Fetching movies...");

    const currentYear = new Date().getFullYear()-10;
    const currentDecadeStart = Math.floor(currentYear / 10) * 10;

    const decades = [...Array(14)].map((_, i) => {
      const startYear = currentDecadeStart - i * 10;
      return `${startYear},${startYear + 9}`;
    });

    const fetchData = async (decades: string[]) => {
      const data = await Promise.all(
        decades.map(async (decade) => {
          const response = await fetch(`/api/top-rated-movies?decade=${decade}`);
          const data = await response.json();
          return { decade, data };
        })
      );

      setDecadeData(data);
    };

    fetchData(decades);
  }, []);

  return (
    <>
      <Head>
        <title>FilmsOfTheDecade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Films Of The Decades</h1>
        </div>
        {decadeData.length > 0 && (
          <div className={styles.listItems}>
            <MovieList decadeData={decadeData} />
          </div>
        )}
      </main>
    </>
  )
}